# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZDWebViewControllerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZDWebViewControllerDemo
  pod 'ReactiveCocoa', '2.5'
  pod 'ZDWebViewController', :path => '../'

  target 'ZDWebViewControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDWebViewControllerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
